/*

 ENDINGTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\GameBoyJam2016\res\pressstart.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define endingtilemapWidth 20
#define endingtilemapHeight 18
#define endingtilemapBank 0

extern unsigned char endingtilemap[];

/* End of ENDINGTILEMAP.H */
