/*

 SRC/MOBILEPLATFORM.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define mobileplatformBank 0
/* Start of tile array. */
extern unsigned char mobileplatform[];

/* End of SRC/MOBILEPLATFORM.H */
