/*

 STAGE2_8.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 30
   Tile set      : stage2_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage2_8Width 20
#define stage2_8Height 30
#define stage2_8Bank 0

extern unsigned char stage2_8[];

/* End of STAGE2_8.H */
