/*

 STAGE3_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_7Width 40
#define stage1_7Height 18
#define stage1_7Bank 0

extern unsigned char stage1_7[];

/* End of STAGE3_1.H */
