/*

 STAGESELECT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : pressstart.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stageSelectWidth 20
#define stageSelectHeight 18
#define stageSelectBank 0

extern unsigned char stageSelect[];

/* End of STAGESELECT.H */
