/*

 STAGE1_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 20
   Tile set      : stage1_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_1Width 80
#define stage1_1Height 20
#define stage1_1Bank 0

extern unsigned char stage1_1[];

/* End of STAGE1_1.H */
