/*

 STAGE2_7.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 36
   Tile set      : stage2_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage2_7Width 20
#define stage2_7Height 36
#define stage2_7Bank 0

extern unsigned char stage2_7[];

/* End of STAGE2_7.H */
