/*

 STAGE3_7.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 62
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage3_7Width 20
#define stage3_7Height 62
#define stage3_7Bank 0

extern unsigned char stage3_7[];

/* End of STAGE3_7.H */
