/*

 STAGE1_3B.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 24 x 18
   Tile set      : D:\GameBoyJam2016\res\stage1_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_3bWidth 24
#define stage1_3bHeight 18
#define stage1_3bBank 0

extern unsigned char stage1_3b[];

/* End of STAGE1_3B.H */
