/*

 STAGE3_8.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 21 x 18
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage3_8Width 21
#define stage3_8Height 18
#define stage3_8Bank 0

extern unsigned char stage3_8[];

/* End of STAGE3_8.H */
