/*

 STAGE2_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : stage2_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage2_1Width 40
#define stage2_1Height 18
#define stage2_1Bank 0

extern unsigned char stage2_1[];

/* End of STAGE2_1.H */
