/*

 STAGE3_5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 51 x 18
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage3_5Width 51
#define stage3_5Height 18
#define stage3_5Bank 0

extern unsigned char stage3_5[];

/* End of STAGE3_5.H */
