/*

 STAGE1_8.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : stage1_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_8Width 20
#define stage1_8Height 18
#define stage1_8Bank 0

extern unsigned char stage1_8[];

/* End of STAGE1_8.H */
