/*

 STAGE1_3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 24 x 60
   Tile set      : D:\GameBoyJam2016\res\stage1_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_3Width 24
#define stage1_3Height 60
#define stage1_3Bank 0

extern unsigned char stage1_3[];

/* End of STAGE1_3.H */
