/*

 STAGE1_5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 48 x 18
   Tile set      : stage1_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage1_5Width 48
#define stage1_5Height 18
#define stage1_5Bank 0

extern unsigned char stage1_5[];

/* End of STAGE1_5.H */
