/*

 STAGE2_5.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 48 x 18
   Tile set      : stage2_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage2_5Width 48
#define stage2_5Height 18
#define stage2_5Bank 0

extern unsigned char stage2_5[];

/* End of STAGE2_5.H */
