/*

 STAGE3_2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 49
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage3_2Width 20
#define stage3_2Height 49
#define stage3_2Bank 0

extern unsigned char stage3_2[];

/* End of STAGE3_2.H */
