/*

 STAGE2_4.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 22 x 30
   Tile set      : stage2_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stage2_4Width 22
#define stage2_4Height 30
#define stage2_4Bank 0

extern unsigned char stage2_4[];

/* End of STAGE2_4.H */
