/*

 STAGEENDING.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : stage3_bg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define stageEndingWidth 32
#define stageEndingHeight 18
#define stageEndingBank 0

extern unsigned char stageEnding[];

/* End of STAGEENDING.H */
